### ISSUE TITLE
Page rules not configured properly

### ISSUE THREAD

**Issue by jorrinpollard** [ellaism/ellaism.github.io#13]
Hey just a heads up that the page rules aren't set up right for the core website or community portal. Visiting https://www.ellaism.org redirects to http://ellaism.org, and visiting https://www.ellaism.io returns the error ERR_CONNECTION_CLOSED. 

This configuration will direct every request to https://www.ellaism.org or https://subdomain.ellaism.org which [is ideal](http://www.yes-www.org/why-use-www/):

Priority 1
www.*.ellaism.org/
Forwarding URL: (Status Code: 301 - Permanent Redirect, Url: https://$1.ellaism.org)

Priority 2
http://ellaism.org/*
Always Use HTTPS

Priority 3
https://ellaism.org/*
Forwarding URL: (Status Code: 301 - Permanent Redirect, Url: https://www.ellaism.org/$1)

**Comment by ellaismer** [comment]
@jorrinpollard There're many arguments that whether one should use the main domain as example.org or www.example.org, but for open source community, the choice is usually example.org. www.example.org is usually configured to redirect to the bare domain example.org. Github also does the same thing, so how about let's just follow this?

I added the rule "Priority 2". Thanks for the catch!

I don't know about Priority 1, though. Looks like nobody would type `www.stats.ellaism.org` right now. And Cloudflare only allows 3 free page rules. So I'd say let's save that.

ellaism.io is not an Ellaism Core project. So unfortunately I cannot change anything about it.

**Comment by ellaismer** [comment]
Ping @riddlez666

**Comment by jorrinpollard** [comment]
Oh I'm fine with the no `www` thing, the insecure redirect was my main concern. Though I think that setup is the most common because creating `A` records is the quickest way to get a custom domain on GH pages up and running. [This post](https://serverfault.com/a/408018) explains why using an `A` record is inconsequential to Github but may not be to one of their customers. If you're using an apex domain through an `ALIAS` or `ANAME` record then there's likely no drawbacks when compared to a `www` subdomain on a static site.

**Comment by ellaismer** [comment]
The bare domain is backed by Cloudflare and it handles load balancing for us. :) Insecure redirect is added. Thanks for this!

I think we can close the issue for now as everything you addressed regarding ellaism.org is fixed. If there's anything else, please feel free to re-open.
